/*
 Source Host           : 127.0.0.1:3306
 Source Schema         : jelly_templates
*/

DROP TABLE IF EXISTS `board`;
CREATE TABLE `board` (
  `Level` int(11) unsigned NOT NULL COMMENT '关卡等级',
  `Board` varchar(127) DEFAULT NULL COMMENT '初始棋盘布局',
  PRIMARY KEY (`Level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='各个关卡等级的初始棋盘布局';

INSERT INTO `board` VALUES (1, 'SHHBBVVHSSHBVSBVHVSBSVSSVHBBSBBBHVHHBHSVSVSSBVBSHBHVHBSBVHHHHHBV');
INSERT INTO `board` VALUES (2, 'HBSHHHBHHVVVVVHHVHHSHSVHHSHHVSBBSVVSVVVSSSHSHHVVVSBBVBHVSHBVBVBB');
INSERT INTO `board` VALUES (3, 'BHHBHSBVBHSBBSHVSSBVBBVVVHHVBHHHBSHHVSBVBVHBHBHHSSHVBVBVBSSHHVVB');
INSERT INTO `board` VALUES (4, 'SSBVBHHSSSHSBVHSVSSHVSBBBSVSSVSSBBHHSVBSSSBHSHHVSHVHBVVSVVVVBBVH');
INSERT INTO `board` VALUES (5, 'BHBHBBHBHVSBHSBBHBHSVHSHHSSHSSBVHVBHVBVSSHHVVVVSBHSVBVBBSVVSHBHS');
INSERT INTO `board` VALUES (6, 'HSSSHHHSVHSSSSHSBHHSBHSHBBVHBBBVVVVSSVVHSSSVVSSVSVBVSSBSVVBVBBHS');
INSERT INTO `board` VALUES (7, 'SVBBBBVSHHHVBHVVHSBVSSVBHHBSBHBVVSHSBVBHHSVBHSVSVSVHSVSHSVBBHHBB');
INSERT INTO `board` VALUES (8, 'SHBVHVVVVSBHHHHVSHVHBSBBBSSBBBHSSHBSBVVBBBVHVHVBVHBVBVHBBBBVSVVS');
INSERT INTO `board` VALUES (9, 'HBVHVHBBSBHHHSHBBBBVHBSSBBVSSHBBSVSVBVHBBVVBVSHSHHBBSHHBSHVSSHSS');
INSERT INTO `board` VALUES (10, 'HSVBVHSBVHBVBSSVVBBSSBHVHVHVBVSHVVSBBVBHBSBBSSVSHBVHSSBBSSBHHBSV');